### ISSUE TITLE
Dataerror

### ISSUE THREAD

**Issue by yuvi3814** [slackapi/template-terms-of-service#5]
Hi I have got below error. Can you please help in identifying the root cause for this error. After the user is added i get this error. Has to do something with the user info verification. 

Error:
NestedError: Can't find dataPath: /THJU1V9RS/UKKAYAEM8. Stopped at THJU1V9RS
    at DataError.NestedError (C:\Slack_App\template-terms-of-service-master\node_modules\node-json-db\lib\Errors.js:7:25)
    at new DataError (C:\Slack_App\template-terms-of-service-master\node_modules\node-json-db\lib\Errors.js:37:33)
    at findData (C:\Slack_App\template-terms-of-service-master\node_modules\node-json-db\JsonDB.js:100:27)
    at recursiveProcessDataPath (C:\Slack_App\template-terms-of-service-master\node_modules\node-json-db\JsonDB.js:127:17)
    at JsonDB._getData (C:\Slack_App\template-terms-of-service-master\node_modules\node-json-db\JsonDB.js:140:16)
    at JsonDB.getData (C:\Slack_App\template-terms-of-service-master\node_modules\node-json-db\JsonDB.js:70:21)
    at Object.initialMessage (C:\Slack_App\template-terms-of-service-master\src\onboard.js:43:19)
    at app.post (C:\Slack_App\template-terms-of-service-master\src\index.js:52:19)
    at Layer.handle [as handle_request] (C:\Slack_App\template-terms-of-service-master\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Slack_App\template-terms-of-service-master\node_modules\express\lib\router\route.js:137:13)
  name: 'DataError',
  stack:
   'NestedError: Can\'t find dataPath: /THJU1V9RS/UKKAYAEM8. Stopped at THJU1V9RS\n    at DataError.NestedError (C:\\Slack_App\\template-terms-of-service-master\\node_module

**Comment by kristiandavid** [comment]
@yuvi3814 did you ever sort this out? I have the same issue.

**Comment by norayna** [comment]
@kristiandavid did you figure it out? 😅 having the same issue
